# This is a basic workflow to help you get started with Actions

name: Fetch CODiS Station List

# Controls when the workflow will run
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # 17:17 , 7:17 , 14:17      6:28, 11:19, 23:59  
    - cron:  '27 4 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "test_schedule"
  codis_schedule:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Chang Timezone to Taipei
      - name: change timezone
        run: sudo timedatectl set-timezone Asia/Taipei

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          ref: 'action' #action branch

      - run: curl https://codis.cwa.gov.tw/api/station_list -o data/codis_station_list.json 

      # Runs a single command using the runners shell
      - name: log time
        run: echo `date` | tee data/fetch.log

      - name: Push 
        run: |
          git config --local user.name github-actions
          git config --local user.email github-actions@github.com
          git add data/
          git commit -m "github action fetch CODiS"
          git push origin action